project:
  type: website
  output-dir: docs

website:
  title: "Lab Math UI"
  search:
      location: navbar
      type: textbox
  navbar:
    search: true
    left:
      - text: "Modul"
        file: modules/modules.qmd
      - text: "Contact"
        file: contact.qmd
  
  sidebar:
    - title: "Exploratory Data Analysis"
      style: "docked"
      contents: EDA/*
    - title: "Struktur Data (C)"
      contents: auto
  page-navigation: false
  page-footer: "Copyright 2024, Lab Departemen Matematika FMIPA UI" 
  
format:
  html:
    theme: flatly
    toc: true




