project:
  type: website
  output-dir: docs

website:
  title: "Lab Praktikum Departemen Matematika FMIPA UI"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - praktikum.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



